# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Micah Taylor
email: micah@micahtaylor.com
description: > # this means to ignore newlines until "baseurl:"
  web developer by day… musician by night… mild mannered photographer somewhere in between... and co-owner of http://brakebread.com/ 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://micahtaylor.github.io/" # the base hostname & protocol for your site
twitter_username: micahtaylor
github_username:  micahtaylor

# Build settings
markdown: kramdown
